---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: docs/TIL
  label: TIL
  create: documents
  match: "*.md"
  templates:
  - post
- type: directory
  path: docs/algorithm
  label: Algorithm
  create: documents
  match: "*.md"
  templates:
  - post
- type: directory
  path: docs/daily
  label: Daily
  create: documents
  match: "*.md"
  templates:
  - post
- type: directory
  path: docs/git
  label: Git
  create: documents
  match: "*.md"
  templates:
  - post
- type: directory
  path: docs/grow
  label: ETC
  create: documents
  match: "*.md"
  templates:
  - post
- type: directory
  path: docs/js
  label: Javscript Fundamental
  create: documents
  match: "*.md"
  templates:
  - post
- type: directory
  path: docs/javascript
  label: ES6+
  create: documents
  match: "*.md"
  templates:
  - post
- type: directory
  path: docs/react
  label: React
  create: documents
  match: "*.md"
  templates:
  - post
- type: directory
  path: docs/nodeJS
  label: NodeJS
  create: documents
  match: "*.md"
  templates:
  - post
- type: directory
  path: docs/os
  label: OS
  create: documents
  match: "*.md"
  templates:
  - post
- type: directory
  path: docs/python
  label: Python
  create: documents
  match: "*.md"
  templates:
  - post
- type: directory
  path: docs/vue
  label: Vue
  create: documents
  match: "*.md"
  templates:
  - post
- type: directory
  path: docs/vuepress
  label: Vuepress
  create: documents
  match: "*.md"
  templates:
  - post
upload_dir: docs/.vuepress/assets
public_path: "../.vuepress/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: docs/.vuepress/dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run build && npm run dev
